### ISSUE TITLE
Use Minetest Texture Pack Completion Checker

### ISSUE THREAD

**Issue by tacotexmex** [MysticTempest/REFI_for_MinetestGame#1]
As a way of showing completeness you may use this badge service in Readme.md.

![](http://minetest-checker.herokuapp.com/game/MysticTempest/REFI_for_MinetestGame.svg)

**Comment by MysticTempest** [comment]
Thank you! I've gone ahead, and added that to the Readme.md; I appreciate it. ^-^

Referenced commit:
539d1e0bfddd6f2b5ccd74421ab092c88b663c0b

**Comment by tacotexmex** [comment]
Forgot to mention that you can also use the URL http://minetest-checker.herokuapp.com/game/MysticTempest/REFI_for_MinetestGame to genererate a list of _what_ is still missing. ☺️

**Comment by tacotexmex** [comment]
Also, feel free to request to join the [Minetest Texturepacks](https://github.com/minetest-texturepacks) organization if you feel like the exposure of a joint organization will benefit your pack. It's a place for high quality, complete or near-completion texture packs. :)
